apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: {{ include "express-example.fullname" . }}
  labels:
    {{- include "express-example.labels" . | nindent 4 }}
spec:
  prefix: {{ .Values.ambassador.prefix}}
  service: {{ include "express-example.fullname" . }}
